namespace HRMS_System.Enums
{
    public enum EmployeeJobRole
    {
        PortWorker = 1,
        ExtraPortWorker = 2,
        PortWorkerRTG = 3,
        PortWorkerTimekeeper = 4,
        GantryOperator = 5,
        QuayCraneOperator = 6,
        QCCraneOperator = 7,
        RTGOperator = 8,
        RTGTrainee = 9,
        ReachStackerOperator = 10,
        PrimeMoverOperator = 11,
        ExtraPrimeMover = 12,
        PMOperator = 13,
        TranstrainerOperator = 14,
        SidelifterOperator = 15,
        ForkliftOperator = 16,
        Winchman = 17,
        WinchmanPooling = 18,
        GangBoss = 19,
        Foreman = 20,
        GearLocker = 21,
        Gatekeeper = 22,
        GateControlChecker = 23,
        AssigningChecker = 24,
        CYChecker = 25,
        DockChecker = 26,
        DocumentVerifier = 27,
        Checker = 28,
        Tireman = 29,

        Mechanic = 30,
        SeniorMechanic = 31,
        JuniorMechanic = 32,
        HeavyEquipmentMechanic = 33,
        JuniorHeavyEquipmentMechanic = 34,
        SeniorHeavyEquipmentMechanic = 35,
        BulkHandlingMechanic = 36,
        IndustrialElectrician = 37,
        JuniorIndustrialElectrician = 38,
        AutomotiveElectrician = 39,
        ElectronicsTechnician = 40,
        JuniorElectronicsTechnician = 41,
        AssistantElectronicsTechnician = 42,
        ReeferContainerTechnician = 43,
        ReeferMonitoringTechnician = 44,
        Welder = 45,
        IndustrialWelder = 46,
        Carpenter = 47,
        Painter = 48,
        Sewer = 49,
        Toolkeeper = 50,
        MaintenanceUtility = 51,
        TechnicalAndMaintenanceStaff = 52,

        OfficeStaff = 53,
        OfficeAssistantToTheOM = 54,
        RecordKeeper = 55,
        Timekeeper = 56,
        HeadTimekeeper = 57,
        PayrollClerk = 58,
        BillingClerk = 59,
        BillingStaff = 60,
        AccountingStaff = 61,
        SubsidiaryLedgerClerk = 62,
        SubsidiaryLedgerInCharge = 63,
        CreditAndCollectionStaff = 64,
        PurchasingClerk = 65,
        HRClerk = 66,
        HRStaff = 67,
        Paymaster = 68,
        AuditStaff = 69,

        MISStaff = 70,
        MISProgrammer = 71,
        JuniorMISProgrammer = 72,
        ITDevelopmentPersonnel = 73,
        JuniorTechnicalSpecialist = 74,
        MISJuniorTechnicalSpecialist = 75,

        ServiceDriver = 76,
        ShuttleDriver = 77,
        ExecutiveDriver = 78,
        AmbulanceDriver = 79,

        CompanyNurse = 80,
        FirstAider = 81,
        SafetyOfficer = 82,
        SecurityAide = 83,
        SSHEMOStaff = 84,
        AssistantPollutionControlOfficer = 85,

        WarehouseStaff = 86,
        WarehouseClerk = 87,
        CFSStaff = 88,
        ISOStaff = 89,
        UtilityPersonnel = 90,
        GeneralServicesUtility = 91,
        GeneralServicesDriver = 92,
        GeneralServicesPainter = 93,
        GeneralServicesCarpenter = 94,

        InsuranceAndClaimsStaff = 95,
        InsuranceAndClaimsInCharge = 96,

        Cashier = 97,
        SatelliteCashier = 98,
        AugmentationCashier = 99,
        Extra = 100,
        OperationsStaff = 101,
        OperationsAndMonitoringStaff = 102,
        OPNMonitoringStaff = 103,
        VOS = 104,

        GeneralManager = 105,
        CEO = 106
    }
}